inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

Style/Documentation:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*.rb'

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/ParameterLists:
  CountKeywordArgs: false
  Max: 5

Metrics/PerceivedComplexity:
  Max: 20
