language: ruby
rvm: 2.5.1
sudo: required
dist: trusty
cache:
  apt: true
  directories:
  - "${HOME}/bin"
addons:
  apt:
    packages:
    - bc
env:
  matrix:
  - INTEGRATION_SPECS=1
  - INTEGRATION_SPECS=0
  global:
  - PATH="${HOME}/bin:${PATH}"
  - SHELLCHECK_URL="https://s3.amazonaws.com/travis-blue-public/binaries/ubuntu/14.04/x86_64/shellcheck-0.4.5.tar.bz2"
  - SHFMT_URL="https://github.com/mvdan/sh/releases/download/v2.0.0/shfmt_v2.0.0_linux_amd64"
before_install:
- mkdir -p "${HOME}/bin"
- if [[ ! -f "${HOME}/bin/shellcheck" ]]; then
    curl -sSL "${SHELLCHECK_URL}" | tar -C "${HOME}/bin" -xjf -;
  fi
- shellcheck --version
- if [[ ! -f "${HOME}/bin/shfmt" ]]; then
    curl -sSL "${SHFMT_URL}" -o "${HOME}/bin/shfmt";
    chmod +x "${HOME}/bin/shfmt";
  fi
- shfmt -version
script:
- ./runtests
- git diff --exit-code
- git diff --cached --exit-code
- if [[ $INTEGRATION_SPECS = 1 ]]; then
    source .example.env;
    bundle exec chirp;
  fi
after_success:
- bundle exec chirp pushback
- bundle exec chirp sendstats
after_failure: bundle exec chirp dumplogs ./log
